// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from "react";
import { auth } from "@/auth"; // Импортируем серверную авторизацию
import HeaderNav from "@/components/HeaderNav"; // Импортируем новый клиентский компонент

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                           children,
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  // Получаем сессию на сервере без задержек для интерфейса
  const session = await auth();

  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">
      <header className="site-header">
        <div className="header-content">
          <h1><Link href="/">Межславянский лексикон</Link></h1>
          <nav>
            {/* Передаем полученную сессию в изолированный список навигации */}
            <HeaderNav session={session} />
          </nav>
        </div>
      </header>
      {children}
      </body>
      </html>
  );
}
