// Собирает словари проверки орфографии Hunspell из словаря и грамматического
// движка: exports/hunspell/isv_Latn.{aff,dic}, isv_Cyrl.{aff,dic}, README.txt,
// metadata.json, isv-hunspell.zip, isv-spellcheck.oxt (расширение LibreOffice).
// Отдаются через /api/downloads/<file>, страница - /downloads.
//
// Только читает interlex.db. На проде - после заметных правок словаря:
//   bash prod.sh run scripts/export-hunspell.ts --apply
// Локально: npx tsx scripts/export-hunspell.ts

import { execSync } from "child_process"
import fs from "fs"
import path from "path"

process.env.DATA_DATABASE_URL ??= `file:${path.resolve(process.cwd(), "interlex.db")}`

const OUT_DIR = path.resolve(process.cwd(), process.env.HUNSPELL_OUT_DIR || "exports/hunspell")

async function main() {
    // Динамический импорт: lib/prisma читает DATA_DATABASE_URL при загрузке.
    const { collectHunspellForms } = await import("@/lib/export/hunspell/collectForms")
    const { buildHunspell, expandHunspell } = await import("@/lib/export/hunspell/compress")
    const { buildArchives, readme } = await import("@/lib/export/hunspell/package")

    const started = Date.now()
    const collected = await collectHunspellForms()
    console.log(`${collected.lexemes} lexemes, ${collected.etymForms} forms (${((Date.now() - started) / 1000).toFixed(1)}s)`)

    const now = new Date()
    const version = `${now.getUTCFullYear()}.${now.getUTCMonth() + 1}.${now.getUTCDate()}`
    let commit: string | null = null
    try { commit = execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] }).toString().trim() } catch { /* не git */ }
    const header = [`Interslavic spell-checking dictionary, version ${version}`, "Generated by scripts/export-hunspell.ts from https://www.interslavic-lexicon.com"]

    const latin = buildHunspell(collected.latin, {
        header,
        wordChars: "-",
        // Первая буква пары - стандартная: подсказка к "jezik" - "język"-подобное "jezyk".
        map: ["eě", "iy", "cčć", "sš", "zž", "(dž)đ(dj)"],
        rep: [["i", "y"], ["y", "i"], ["e", "ě"], ["ě", "e"], ["dj", "dž"], ["đ", "dž"], ["ch", "h"], ["w", "v"], ["ł", "l"]],
    })
    const cyrillic = buildHunspell(collected.cyrillic, {
        header,
        wordChars: "-",
        map: ["еє", "иы", "(дж)џђ", "(лј)љ", "(нј)њ", "чћ"],
        rep: [["и", "ы"], ["ы", "и"], ["е", "є"], ["й", "ј"], ["я", "ја"], ["ю", "ју"], ["щ", "шч"]],
    })

    // Выгрузка обязана разворачиваться ровно в собранные слова.
    for (const [name, dict, source] of [["isv_Latn", latin, collected.latin], ["isv_Cyrl", cyrillic, collected.cyrillic]] as const) {
        const expanded = expandHunspell(dict.aff, dict.dic)
        const expected = new Set(source.flat().filter((w) => w && !/[\s/]/.test(w)))
        if (expanded.size !== expected.size || [...expected].some((w) => !expanded.has(w))) throw new Error(`${name}: expansion does not match the collected forms`)
        console.log(`${name}: ${dict.stats.words} words -> ${dict.stats.entries} entries, ${dict.stats.classes} classes; aff ${(dict.aff.length / 1024).toFixed(0)} KB, dic ${(dict.dic.length / 1024).toFixed(0)} KB`)
    }

    const meta = { version, builtAt: now.toISOString(), commit, lexemes: collected.lexemes, stats: { isv_Latn: latin.stats, isv_Cyrl: cyrillic.stats } }
    const files: Record<string, string> = {
        "isv_Latn.aff": latin.aff, "isv_Latn.dic": latin.dic,
        "isv_Cyrl.aff": cyrillic.aff, "isv_Cyrl.dic": cyrillic.dic,
        "README.txt": readme(meta),
    }
    const { zip, oxt } = buildArchives(files, version)

    // Пишем во временный каталог и подменяем целиком: страница /downloads не
    // должна увидеть половину новых файлов и половину старых.
    const tmp = `${OUT_DIR}.tmp-${process.pid}`
    fs.rmSync(tmp, { recursive: true, force: true })
    fs.mkdirSync(tmp, { recursive: true })
    for (const [name, content] of Object.entries(files)) fs.writeFileSync(path.join(tmp, name), content)
    fs.writeFileSync(path.join(tmp, "isv-hunspell.zip"), zip)
    fs.writeFileSync(path.join(tmp, "isv-spellcheck.oxt"), oxt)
    fs.writeFileSync(path.join(tmp, "metadata.json"), JSON.stringify(meta, null, 2))
    const old = `${OUT_DIR}.old-${process.pid}`
    if (fs.existsSync(OUT_DIR)) fs.renameSync(OUT_DIR, old)
    fs.renameSync(tmp, OUT_DIR)
    fs.rmSync(old, { recursive: true, force: true })
    console.log(`-> ${path.relative(process.cwd(), OUT_DIR)} (${((Date.now() - started) / 1000).toFixed(1)}s total)`)
    process.exit(0)
}

main().catch((e) => {
    console.error(e)
    process.exit(1)
})
